### PR TITLE
Add option to save fake pixel cloud from GDEM

### PR DESCRIPTION
**Pull request by llabatal**
Note that at the same time, a merge request will be performed on the python repository (update of swot/bin/l2pixc_to_rivertile.py)

### CODE REVIEW

**Comment by alexfore** [comment]
Are we just trying to save the GDEM PIXC here with all of these changes (in RiverObs and python)? Just using the fake_pixc_from_gdem.py script instead.  If you want to save them use that script at the level you want to save them instead of this hierarchy of changes.

**Comment by llabatal** [comment]
Hello, using the fake_pixc_from_gdem.py will not be enough to cover my need. I need to enable this option at a top level (from module l2pixc_to_rivertile.py of python repo) to handle severals simulations/processing at the same time. Thank you in advance,

**Comment by alexfore** [comment]
I going to modify the other code and close this.  It isn't appropriate to talk about those changes here.  Email me if you want to talk, I don't know your email.

**Comment by llabatal** [comment]
So what you're saying is that you will implement this modification only in the python repository part instead? Please see the corresponding PR that is related to this subject. Thank you

**Pull request closed without merging**
